import { HotelRoom, RoomType, Reservation, HotelFolio, DashboardStats } from './types';

export const INITIAL_ROOM_TYPES: RoomType[] = [
  {
    id: 'rt-superior',
    name: 'Superior Room',
    code: 'SUP',
    basePrice: 3000,
    capacityAdults: 2,
    capacityChildren: 1,
    bedType: 'Queen Bed + Living Room',
    sizeSqm: 32, // 348 sq ft
    description: 'Spacious room with air-conditioning, separate living room, 40" TV, complimentary Wi-Fi, tea/coffee maker, and bottled water.',
    amenities: ['Air Conditioning', 'Separate Living Room', 'High-Speed Wi-Fi', '40" Smart TV', 'Tea & Coffee Maker', 'Bottled Water'],
    imageUrl: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'rt-deluxe-1bhk',
    name: 'Deluxe One Bedroom Apartment (1-BHK)',
    code: '1BHK',
    basePrice: 4000,
    capacityAdults: 3,
    capacityChildren: 2,
    bedType: 'Queen Bed + Sofa Bed',
    sizeSqm: 50, // 539 sq ft
    description: 'Fully furnished 1-BHK apartment with equipped kitchen facility, living room, air-conditioning, and high-speed internet.',
    amenities: ['Fully Equipped Kitchen', 'Air Conditioning', 'Separate Living Room', '40" Smart TV', 'Refrigerator', 'Dining Area'],
    imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'rt-executive-2bhk',
    name: 'Executive Two Bedroom Apartment (2-BHK)',
    code: '2BHK',
    basePrice: 6000,
    capacityAdults: 5,
    capacityChildren: 2,
    bedType: '2 Queen Bedrooms + Large Living Room',
    sizeSqm: 92, // 989 sq ft
    description: 'Expansive 2-BHK apartment ideal for families and medical stay patients. Complete kitchen, 2 private bathrooms, and dining hall.',
    amenities: ['2 Bedrooms', 'Complete Kitchen', '2 Bathrooms', 'Spacious Living Salon', 'Washing Machine', 'Daily Housekeeping'],
    imageUrl: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=80',
  },
];

export const INITIAL_ROOMS: HotelRoom[] = [
  // First Floor (Rooms 101 - 106)
  { id: 'r-101', number: '101', floor: 1, roomTypeId: 'rt-superior', status: 'occupied', housekeepingStatus: 'clean', currentReservationId: 'res-101', currentGuestName: 'Muhammed Basheer' },
  { id: 'r-102', number: '102', floor: 1, roomTypeId: 'rt-superior', status: 'available', housekeepingStatus: 'clean' },
  { id: 'r-103', number: '103', floor: 1, roomTypeId: 'rt-superior', status: 'reserved', housekeepingStatus: 'clean', currentReservationId: 'res-103', currentGuestName: 'Rajesh Kumar' },
  { id: 'r-104', number: '104', floor: 1, roomTypeId: 'rt-superior', status: 'cleaning', housekeepingStatus: 'dirty' },
  { id: 'r-105', number: '105', floor: 1, roomTypeId: 'rt-superior', status: 'available', housekeepingStatus: 'clean' },
  { id: 'r-106', number: '106', floor: 1, roomTypeId: 'rt-superior', status: 'maintenance', housekeepingStatus: 'out_of_order', notes: 'AC service' },

  // Second Floor (Rooms 201 - 206 - Deluxe 1-BHK)
  { id: 'r-201', number: '201', floor: 2, roomTypeId: 'rt-deluxe-1bhk', status: 'occupied', housekeepingStatus: 'clean', currentReservationId: 'res-201', currentGuestName: 'Dr. Faizal Rahman' },
  { id: 'r-202', number: '202', floor: 2, roomTypeId: 'rt-deluxe-1bhk', status: 'available', housekeepingStatus: 'clean' },
  { id: 'r-203', number: '203', floor: 2, roomTypeId: 'rt-deluxe-1bhk', status: 'reserved', housekeepingStatus: 'clean', currentReservationId: 'res-203', currentGuestName: 'Anil Nambiar' },
  { id: 'r-204', number: '204', floor: 2, roomTypeId: 'rt-deluxe-1bhk', status: 'occupied', housekeepingStatus: 'clean', currentReservationId: 'res-204', currentGuestName: 'Priya Varma' },
  { id: 'r-205', number: '205', floor: 2, roomTypeId: 'rt-deluxe-1bhk', status: 'cleaning', housekeepingStatus: 'inspecting' },
  { id: 'r-206', number: '206', floor: 2, roomTypeId: 'rt-deluxe-1bhk', status: 'available', housekeepingStatus: 'clean' },

  // Third Floor (Rooms 301 - 304 - Executive 2-BHK)
  { id: 'r-301', number: '301', floor: 3, roomTypeId: 'rt-executive-2bhk', status: 'occupied', housekeepingStatus: 'clean', currentReservationId: 'res-301', currentGuestName: 'Suresh Menon' },
  { id: 'r-302', number: '302', floor: 3, roomTypeId: 'rt-executive-2bhk', status: 'reserved', housekeepingStatus: 'clean', currentReservationId: 'res-302', currentGuestName: 'Abdul Kareem (NRI)' },
  { id: 'r-303', number: '303', floor: 3, roomTypeId: 'rt-executive-2bhk', status: 'available', housekeepingStatus: 'clean' },
  { id: 'r-304', number: '304', floor: 3, roomTypeId: 'rt-executive-2bhk', status: 'cleaning', housekeepingStatus: 'dirty' },
];

export const INITIAL_RESERVATIONS: Reservation[] = [
  {
    id: 'res-101',
    bookingCode: 'LAN-2026-101',
    source: 'walk_in',
    guest: {
      id: 'g-101',
      firstName: 'Muhammed',
      lastName: 'Basheer',
      email: 'm.basheer@example.com',
      phone: '+91 94470 12345',
      identityType: 'national_id',
      identityNumber: 'AADHAAR-8921-3849',
      vip: false,
    },
    roomId: 'r-101',
    roomNumber: '101',
    roomTypeId: 'rt-superior',
    roomTypeName: 'Superior Room',
    checkInDate: '2026-09-11',
    checkOutDate: '2026-09-14',
    nights: 3,
    adults: 2,
    children: 1,
    status: 'checked_in',
    totalAmount: 9000,
    depositPaid: 9000,
    specialRequests: 'Visiting Al-Shifa Hospital. Requested ground floor.',
    createdAt: '2026-09-11',
  },
  {
    id: 'res-103',
    bookingCode: 'MMT-IN-88910',
    source: 'makemytrip',
    guest: {
      id: 'g-103',
      firstName: 'Rajesh',
      lastName: 'Kumar',
      email: 'rajesh.k@example.com',
      phone: '+91 98950 55443',
      identityType: 'national_id',
      identityNumber: 'AADHAAR-4491-0029',
      vip: false,
    },
    roomId: 'r-103',
    roomNumber: '103',
    roomTypeId: 'rt-superior',
    roomTypeName: 'Superior Room',
    checkInDate: '2026-09-12',
    checkOutDate: '2026-09-15',
    nights: 3,
    adults: 2,
    children: 0,
    status: 'confirmed',
    totalAmount: 9000,
    depositPaid: 3000,
    specialRequests: 'Late check-in at 7 PM',
    createdAt: '2026-09-10',
  },
  {
    id: 'res-201',
    bookingCode: 'BDC-IN-44210',
    source: 'booking_com',
    guest: {
      id: 'g-201',
      firstName: 'Dr. Faizal',
      lastName: 'Rahman',
      email: 'faizal.dr@example.com',
      phone: '+91 97451 99887',
      identityType: 'national_id',
      identityNumber: 'AADHAAR-7712-4432',
      vip: true,
      notes: 'Doctor at Al-Shifa Hospital, extended medical stay',
    },
    roomId: 'r-201',
    roomNumber: '201',
    roomTypeId: 'rt-deluxe-1bhk',
    roomTypeName: 'Deluxe One Bedroom Apartment (1-BHK)',
    checkInDate: '2026-09-10',
    checkOutDate: '2026-09-15',
    nights: 5,
    adults: 2,
    children: 1,
    status: 'checked_in',
    totalAmount: 20000,
    depositPaid: 20000,
    createdAt: '2026-09-08',
  },
  {
    id: 'res-203',
    bookingCode: 'LAN-WI-203',
    source: 'walk_in',
    guest: {
      id: 'g-203',
      firstName: 'Anil',
      lastName: 'Nambiar',
      email: 'anil.nambiar@example.com',
      phone: '+91 94955 66778',
      identityType: 'driving_license',
      identityNumber: 'KL-53-2019-0044',
      vip: false,
    },
    roomId: 'r-203',
    roomNumber: '203',
    roomTypeId: 'rt-deluxe-1bhk',
    roomTypeName: 'Deluxe One Bedroom Apartment (1-BHK)',
    checkInDate: '2026-09-12',
    checkOutDate: '2026-09-14',
    nights: 2,
    adults: 2,
    children: 0,
    status: 'confirmed',
    totalAmount: 8000,
    depositPaid: 4000,
    createdAt: '2026-09-12',
  },
  {
    id: 'res-301',
    bookingCode: 'LAN-VIP-301',
    source: 'direct',
    guest: {
      id: 'g-301',
      firstName: 'Suresh',
      lastName: 'Menon',
      email: 'suresh.menon@example.com',
      phone: '+91 98470 33221',
      identityType: 'national_id',
      identityNumber: 'AADHAAR-9901-2244',
      vip: true,
      notes: 'Family medical treatment. Requires kitchen utensils kit.',
    },
    roomId: 'r-301',
    roomNumber: '301',
    roomTypeId: 'rt-executive-2bhk',
    roomTypeName: 'Executive Two Bedroom Apartment (2-BHK)',
    checkInDate: '2026-09-09',
    checkOutDate: '2026-09-16',
    nights: 7,
    adults: 4,
    children: 1,
    status: 'checked_in',
    totalAmount: 42000,
    depositPaid: 42000,
    createdAt: '2026-09-01',
  },
];

export const INITIAL_FOLIOS: HotelFolio[] = [
  {
    id: 'fol-101',
    reservationId: 'res-101',
    folioNumber: 'FOL-2026-0101',
    guestName: 'Muhammed Basheer',
    roomNumber: '101',
    items: [
      { id: 'fi-1', date: '2026-09-11', description: 'Superior Room - 3 Nights @ ₹3,000/night', category: 'room', quantity: 3, unitPrice: 3000, total: 9000 },
      { id: 'fi-2', date: '2026-09-11', description: 'Extra Bed & Linen Set', category: 'other', quantity: 1, unitPrice: 500, total: 500 },
      { id: 'fi-3', date: '2026-09-12', description: 'Laundry Express Service', category: 'laundry', quantity: 1, unitPrice: 350, total: 350 },
      { id: 'fi-4', date: '2026-09-11', description: 'GST (12% on Hotel Accommodations)', category: 'tax', quantity: 1, unitPrice: 1080, total: 1080 },
    ],
    payments: [
      { id: 'fp-1', date: '2026-09-11', amount: 9000, method: 'upi', reference: 'UPI-GPAY-98214' },
    ],
    totalCharges: 10930,
    totalPaid: 9000,
    balanceDue: 1930,
    isClosed: false,
    odooInvoiceId: 1042,
  },
  {
    id: 'fol-201',
    reservationId: 'res-201',
    folioNumber: 'FOL-2026-0201',
    guestName: 'Dr. Faizal Rahman',
    roomNumber: '201',
    items: [
      { id: 'fi-21', date: '2026-09-10', description: 'Deluxe 1-BHK Apartment - 5 Nights @ ₹4,000/night', category: 'room', quantity: 5, unitPrice: 4000, total: 20000 },
      { id: 'fi-22', date: '2026-09-10', description: 'Kitchen Gas & Utensils Setup Charge', category: 'other', quantity: 1, unitPrice: 800, total: 800 },
      { id: 'fi-23', date: '2026-09-11', description: 'GST (12%)', category: 'tax', quantity: 1, unitPrice: 2400, total: 2400 },
    ],
    payments: [
      { id: 'fp-21', date: '2026-09-10', amount: 23200, method: 'credit_card', reference: 'POS-HDFC-991' },
    ],
    totalCharges: 23200,
    totalPaid: 23200,
    balanceDue: 0,
    isClosed: false,
    odooInvoiceId: 1045,
  },
  {
    id: 'fol-301',
    reservationId: 'res-301',
    folioNumber: 'FOL-2026-0301',
    guestName: 'Suresh Menon',
    roomNumber: '301',
    items: [
      { id: 'fi-31', date: '2026-09-09', description: 'Executive 2-BHK Apartment - 7 Nights @ ₹6,000/night', category: 'room', quantity: 7, unitPrice: 6000, total: 42000 },
      { id: 'fi-32', date: '2026-09-10', description: 'Daily Buffet Breakfast (4 Pax x 7 Days)', category: 'restaurant', quantity: 7, unitPrice: 1000, total: 7000 },
      { id: 'fi-33', date: '2026-09-09', description: 'GST (12%)', category: 'tax', quantity: 1, unitPrice: 5880, total: 5880 },
    ],
    payments: [
      { id: 'fp-31', date: '2026-09-09', amount: 42000, method: 'bank_transfer', reference: 'NEFT-SBI-44021' },
    ],
    totalCharges: 54880,
    totalPaid: 42000,
    balanceDue: 12880,
    isClosed: false,
  },
];
